---
- name: Add reboot cron
  when: reboot_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Remove reboot cron
  when: reboot_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml
